"""Record real native Tk events and frame delivery during manual interaction.

Development telemetry only; never injects input or captures the desktop. Tk
idle paint completion is measured, not compositor/vsync or monitor latency.
Close the window to finalize the JSON. No input means no physical-input claim.
"""
import argparse
from datetime import datetime,timezone
import hashlib
import importlib.util
import json
from pathlib import Path
import platform
import statistics
import sys
from threading import Lock
import time


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output',type=Path,required=True)
    parser.add_argument('--runtime',type=Path)
    parser.add_argument('--geojson',type=Path)
    parser.add_argument('--scripted-views',action='store_true',help='Drive two own model edits (no input injection), then close automatically')
    args=parser.parse_args()
    if args.runtime:sys.path.insert(0,str(args.runtime.resolve()))
    import azimlib as azl
    from azimlib.backends.tk import FigureWindow
    from measure_process_memory import process_memory
    records=[];lock=Lock();began=time.perf_counter();initial_memory=process_memory()
    if sys.platform=='win32':
        import ctypes
        kernel=ctypes.WinDLL('kernel32');kernel.GetTickCount64.restype=ctypes.c_ulonglong
        ticks=lambda:kernel.GetTickCount64()&0xffffffff
    else:ticks=None
    def record(kind,**data):
        with lock:records.append(dict(kind=kind,t=time.perf_counter()-began,**data))
    def extentkey():return [list(ax.get_extent()) for ax in fig.axes]
    if args.geojson:
        from benchmark_detailed_map import build
        fig,_,read,input_hash=build(args.geojson)
        case='original-SP-645 + synthetic mesh/contour/1200 points'
    else:
        from show_viewer_comparison import build
        fig=build(azl);read=0;input_hash=None;case='bundled Brazil + synthetic route'
    original_compose=fig.to_scene
    def compose(*a,**kw):
        start=time.perf_counter();scene=original_compose(*a,**kw)
        record('compose',seconds=time.perf_counter()-start,items=len(scene.items))
        return scene
    fig.to_scene=compose

    class Instrumented(FigureWindow):
        def _present(self,scene,image,**kwargs):
            start=time.perf_counter();super()._present(scene,image,**kwargs)
            frame=dict(extents=[list(m['extent']) for m in scene.maps],complete=kwargs.get('complete',True),
                pixels=list(image.size),delivery_seconds=time.perf_counter()-start,
                cache_hits=self._raster_cache.hits,cache_misses=self._raster_cache.misses)
            record('frame_delivery',**frame)
            self.window.after_idle(lambda:record('tk_paint_idle',**frame))
        def close(self):
            if self.closed:return
            record('close_requested');super().close();save(final=True)

    def instrument(name):
        original=getattr(FigureWindow,name)
        def call(self,*a,**kw):
            start=time.perf_counter();age=None;native_time=None
            if a and hasattr(a[0],'time'):
                try:native_time=int(a[0].time)
                except (ValueError,TypeError):pass
                if native_time and ticks:
                    value=(ticks()-native_time)&0xffffffff
                    if value<60000:age=value
            original(self,*a,**kw)
            event=a[0] if a else None
            record('input',action=name,seconds=time.perf_counter()-start,native_event_time=native_time,
                estimated_dispatch_age_ms=age,x=getattr(event,'x',None),y=getattr(event,'y',None),
                button_state=getattr(event,'state',None),extents=extentkey(),mode=self.mode)
        setattr(Instrumented,name,call)
    for name in ('press','motion','release','wheel','enter','leave','home','back','forward'):
        instrument(name)
    root=Path(azl.__file__).parent
    header=dict(schema_version=1,started_utc=datetime.now(timezone.utc).isoformat(),case=case,input_sha256=input_hash,
        python=platform.python_version(),platform=platform.platform(),azimlib=azl.__version__,read_seconds=read,
        scripted_model_edits=args.scripted_views,
        tool_sha256=hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        runtime_sha256={str(p.relative_to(root)).replace('\\','/'):hashlib.sha256(p.read_bytes()).hexdigest()
                        for p in sorted(root.rglob('*.py'))},
        initial_memory=initial_memory,
        scope=['Visible native Tk window; input comes from native bindings, never generated by this script.',
               'Windows event timestamp compared with GetTickCount64: approximate dispatch age at native timer granularity.',
               'Frame delivery includes PhotoImage/canvas command; subsequent Tk idle records bound scheduled Tk painting, not compositor/vsync/monitor completion.',
               'Input-to-frame associations require matching recorded geographic extents; intermediate old frames are not latest-view latency.',
               'Manual observation is recorded separately; these timings do not verify screenshot appearance.'])
    def save(final=False):
        with lock:snapshot=list(records)
        inputs=[r for r in snapshot if r['kind']=='input'];ages=[r['estimated_dispatch_age_ms'] for r in inputs if r['estimated_dispatch_age_ms'] is not None]
        heartbeat=[r['t'] for r in snapshot if r['kind']=='heartbeat'];gaps=[(b-a)*1000 for a,b in zip(heartbeat,heartbeat[1:])]
        summary=dict(native_events=len(inputs),actions={n:sum(r['action']==n for r in inputs) for n in ('press','motion','release','wheel','enter','leave','home','back','forward')},
            handler_max_ms=max((r['seconds']*1000 for r in inputs),default=None),
            dispatch_age_median_ms=statistics.median(ages) if ages else None,dispatch_age_max_ms=max(ages,default=None),
            heartbeat_max_gap_ms=max(gaps,default=None),paint_idle_records=sum(r['kind']=='tk_paint_idle' for r in snapshot))
        report=dict(**header,final=final,summary=summary,records=snapshot,current_memory=process_memory())
        args.output.parent.mkdir(parents=True,exist_ok=True)
        args.output.write_text(json.dumps(report,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
    viewer=Instrumented(fig,initial_draw=False);fig.canvas=viewer;fig._viewer=viewer
    viewer.window.title('Azimlib · passo 4 · '+('São Paulo detalhado' if args.geojson else 'Brasil'))
    viewer.window.geometry('+40+80' if not args.geojson else '+710+80')
    for name in ('renderer','controlled_renderer','preview_renderer'):
        original=getattr(viewer._pan_raster,name)
        def measured(*a,original=original,name=name,**kw):
            start=time.perf_counter()
            try:return original(*a,**kw)
            finally:record('raster',renderer=name,seconds=time.perf_counter()-start)
        setattr(viewer._pan_raster,name,measured)
    def heartbeat():
        if not viewer.closed:record('heartbeat');viewer.window.after(20,heartbeat)
    def periodic():
        if not viewer.closed:save();viewer.window.after(1500,periodic)
    viewer.draw();viewer.window.update_idletasks();viewer.widget.focus_set()
    record('ready',extent=extentkey(),pixels=list(viewer._image.size),tk=viewer.window.tk.call('info','patchlevel'),
           window_state=viewer.window.state(),canvas_viewable=bool(viewer.widget.winfo_viewable()))
    heartbeat();periodic();print('Visible viewer ready. Only manual input is recorded; close to finalize.',flush=True)
    if args.scripted_views:
        home=fig.axes[0].get_extent();w,e,s,n=home
        stages=iter([('new_pan',(w+.4,e+.4,s+.2,n+.2)),('returned_home',home)])
        def advance():
            try:name,extent=next(stages)
            except StopIteration:viewer.close();return
            record('model_edit',stage=name,extent=list(extent))
            fig.axes[0].set_extent(extent);viewer._async_pan=True;viewer.draw_idle()
            def settled():
                if viewer.closed:return
                busy=viewer._pan_raster.busy() or viewer._pending is not None or viewer._async_pan
                if busy:viewer.window.after(20,settled)
                else:
                    record('model_settled',stage=name,extent=extentkey(),canvas_viewable=bool(viewer.widget.winfo_viewable()))
                    viewer.window.after(600,advance)
            viewer.window.after(20,settled)
        viewer.window.after(1000,advance)
    viewer.window.mainloop()


if __name__=='__main__':main()
